CREATE TABLE USER
(
    ID                 BIGINT PRIMARY KEY AUTO_INCREMENT,
    USERNAME           VARCHAR(10) UNIQUE,
    ENCRYPTED_PASSWORD VARCHAR(100),
    AVATAR             VARCHAR(100),
    CREATED_AT         DATETIME,
    UPDATED_AT         DATETIME
);