CREATE TABLE BLOG
(
    ID          BIGINT PRIMARY KEY AUTO_INCREMENT,
    USER_ID     BIGINT,
    TITTLE      VARCHAR(100),
    DESCRIPTION VARCHAR(100),
    CONTENT     TEXT,
    CREATED_AT  DATETIME,
    UPDATED_AT  DATETIME
);